### ISSUE TITLE
@atomic error

### ISSUE THREAD

**Issue by grant-roy** [EpistasisLab/ebic.jl#11]
I'm getting an error running the example on Julia 1.7.2: 
<img width="1025" alt="Screen Shot 2022-04-12 at 12 24 19 PM" src="https://user-images.githubusercontent.com/1839666/163038453-fa81d5f3-69b8-4d3c-816a-fed7c88c3af1.png">

The code works in Julia 1.6.6 so I assume this is a change in 1.7.

**Comment by prenc** [comment]
Yes, in Julia 1.7.2 [@atomic was added to Base](https://docs.julialang.org/en/v1/base/multi-threading/#Base.@atomic) and it shadows the one exported from the CUDA.jl package.

@grant-roy thank you for opening the issue.

**Comment by grant-roy** [comment]
Sure, happy to help spot any issues.
